### PR TITLE
DAA: Implement Mountainous Smoke, plus some fixes

### PR DESCRIPTION
**Pull request by starg09**
Not 100% liking this implementation (since the card ends up in the hand for a brief moment), but it should work fine. Hopefully the global value stops Jirachi appropriately.

### CODE REVIEW

**Comment by flagrama** [comment]
Is there a particular reason you're using retrieveAndStore even though you're not using the value you're retrieving? Aside from that I don't have any major objections to this. Hopefully it works. Are there any other cards with effects when pulled from the prizes that need to check this?

**Comment by starg09** [comment]
Hmm, my train of thought went with it being useful but nah, will update it.

**Comment by starg09** [comment]
[STARLY_153](https://trello.com/c/D2MinOJN/587-starly153)

**Comment by starg09** [comment]
[ARIADOS_105](https://trello.com/c/aMnXOp2T/539-ariados105)

**Comment by starg09** [comment]
[LIEPARD_110](https://trello.com/c/bGj4zXpq/544-liepard110)

**Comment by starg09** [comment]
[HYDREIGON_113](https://trello.com/c/w8oN8jQ4/547-hydreigon113)

**Comment by starg09** [comment]
[SHIINOTIC_81](https://trello.com/c/S3IxHwsF/515-shiinotic81)

**Comment by starg09** [comment]
[RHYPERIOR_V_98](https://trello.com/c/kunlTSZE/532-rhyperiorv98)

**Comment by starg09** [comment]
[ETERNATUS_V_127](https://trello.com/c/wfRQcaft/561-eternatusv127)

**Comment by luongthomas** [comment]
Builds fine and tested behavior locally

**Pull request merged**
