### PR TITLE
Add SWSH Promos 033-042 + Updates for Darkness Ablaze based on "official" set list

### PR DESCRIPTION
**Pull request by starg09**
Leaving as a draft, but this should in theory cover the main differences regarding ordering, numbering, and trainer/energy name changes. Some abilities got updated, but some may still need updating. And a similar update needs to be done on [carddb](https://github.com/tcgone/carddb/).

Some coded-and-tested cards were removed, which can be taken from here whenever SSH3.5 is worked on (e.g. Gardevoir V/VMAX). Eevee and Flareon are now added as SWSH Promos (alongside the 4 prerelease cards, and some reprints).

Also updated the label in `Collection.java`, as to use the official one.

Source for changes: https://www.pokebeach.com/2020/07/complete-darkness-ablaze-english-set-list

### CODE REVIEW

**Comment by starg09** [comment]
Marking this as open, being more confident after seeing some early opening videos, and with [some cards officially revealed on the Pokémon website](https://www.pokemon.com/us/pokemon-news/centiskorch-vmax-galarian-slowbro-v-and-more-in-pokemon-tcg-sword-shield-darkness-ablaze/).

**Comment by starg09** [comment]
[GALARIAN_DARMANITAN_46](https://trello.com/c/kGswwllK/480-galariandarmanitan46)

**Comment by starg09** [comment]
[GALARIAN_SIRFETCH_D_88](https://trello.com/c/3MzxEmOE/522-galariansirfetchd88)

**Comment by starg09** [comment]
[GALARIAN_SLOWBRO_V_67](https://trello.com/c/JIxzCBcV/501-galarianslowbrov67)

**Comment by starg09** [comment]
[MEW_V_68](https://trello.com/c/3rLa2bhI/502-mewv68)

**Comment by axpendix** [comment]
Hey, what is the status of this one?

**Comment by starg09** [comment]
> Hey, what is the status of this one?

Currently waiting on other DAA PRs to be merged before applying them here. #880 is done so I'll get to that later, If @flagrama prefers to wait for this rebuild (or apply patches directly on the `daa-rebuild` branch) before continuing with their fixes for #879, that could also work (and save the need to port that over 😅)

carddb still needs to be updated, as well as replacing the scans with the actual cards instead of proxies.

**Comment by starg09** [comment]
With carddb and scans updated, will merge this as to allow testing to be done on dev (whenever building is fixed)

**Pull request merged**
