### PR TITLE
Fix Rebel Clash card names

### PR DESCRIPTION
**Pull request by scoot404**
Secret Rare Perrserker was missing "Galarian" from it's name and Big Charm was named Giant Charm.

### CODE REVIEW

**Comment by luongthomas** [comment]
This will have to be changed on carddb too otherwise we won't be able to call the card on dev server as it is

**Comment by scoot404** [comment]
I'm currently making more changes and also making changes on carddb as well.

**Comment by scoot404** [comment]
[EISCUE_V_55](https://trello.com/c/g4UeueSg/276-eiscuev55)

**Comment by scoot404** [comment]
Should be merged after [this PR in carddb](https://github.com/axpendix/carddb/pull/29) is merged.

**Comment by luongthomas** [comment]
[CURSED_SHOVEL_156](https://trello.com/c/XOxBuhHr/377-cursedshovel156)

**Comment by luongthomas** [comment]
[DAN_157](https://trello.com/c/rGY4GCF3/378-dan157)

**Pull request merged**
