### PR TITLE
Strike energy

### PR DESCRIPTION
**Pull request by flagrama**

### CODE REVIEW

**Comment by flagrama** [comment]
[SINGLE_STRIKE_ENERGY_183](https://trello.com/c/WKhficnc/1097-singlestrikeenergy183)

**Comment by flagrama** [comment]
[RAPID_STRIKE_ENERGY_182](https://trello.com/c/jdQ2YsJ3/1096-rapidstrikeenergy182)

**Comment by flagrama** [comment]
[RAPID_STRIKE_ENERGY_140](https://trello.com/c/IaN9iUVV/1054-rapidstrikeenergy140)

**Comment by flagrama** [comment]
[SINGLE_STRIKE_ENERGY_183](https://trello.com/c/WKhficnc/1097-singlestrikeenergy183)

**Review by luongthomas — APPROVED** [review]
👍

**Pull request merged**
