### PR TITLE
Remove STAGE1 type from VMAX Pokemon

### PR DESCRIPTION
**Pull request by luongthomas**
This PR will remove all `STAGE1` subtypes from `VMAX` Pokemon since this is an incorrect categorization.

I've fixed the `RandomDeckGenerator` to not crash when it doesn't see `STAGE1` on `POKEMON_V/VMAX` evolution lines.

### CODE REVIEW

**Comment by starg09** [comment]
I'd suggest also removing the workarounds for VMAX (**not** reverting the commit for it, some fixes were applied later on)
* Ditto Prism Star (LOT)
* Bodybuilding Dumbbells (BUS)
* Evelyn (TEU)
* Rowlet & Alolan Exeggutor GX (UNM)

**Comment by luongthomas** [comment]
> I'd suggest also removing the workarounds for VMAX (**not** reverting the commit for it, some fixes were applied later on)
> 
> * Ditto Prism Star (LOT)
> * Bodybuilding Dumbbells (BUS)
> * Evelyn (TEU)
> * Rowlet & Alolan Exeggutor GX (UNM)

Good idea, I've added a commit to remove the workaround code

**Comment by luongthomas** [comment]
Do not merge this yet until some changes on the backend are configured

**Comment by flagrama** [comment]
Hmm, I'm still getting the error from meowth when making a random standard deck from time to time. Is the random deck fix not actually in the dev pipeline yet?

**Comment by luongthomas** [comment]
> Hmm, I'm still getting the error from meowth when making a random standard deck from time to time. Is the random deck fix not actually in the dev pipeline yet?

It's not in the dev pipeline yet but it should be fairly soon, I believe @axpendix is working on it .  Once it is in, we can merge this PR

**Pull request merged**
