### PR TITLE
Undaunted Set Fixes

### PR DESCRIPTION
**Pull request by luongthomas**
Fixes for the Gen4 set Undaunted on Trello

### CODE REVIEW

**Comment by luongthomas** [comment]
[UNOWN_40](https://trello.com/c/xPkFepJR/261-unown40)

**Comment by luongthomas** [comment]
[SLOWPOKE_66](https://trello.com/c/dcmTSI3R/287-slowpoke66)

**Comment by luongthomas** [comment]
[LAIRON_29](https://trello.com/c/SnntQp8G/250-lairon29)

**Comment by luongthomas** [comment]
[SCYTHER_36](https://trello.com/c/tDNFGNNF/257-scyther36)

**Review by starg09 — APPROVED** [review]

**Pull request merged**
