### PR TITLE
Optimized rockPaperScissors

### PR DESCRIPTION
**Pull request by ufodynasty**
Its not like it needs it but it was bugging me the first time

### CODE REVIEW

**Comment by flagrama** [comment]
I don't think modulus will work for this. I tested it here, and it really only works with positive numbers so not all paths seems to work as intended. http://tpcg.io/rXb0sBVL

**Comment by ufodynasty** [comment]
:(

**Comment by flagrama** [comment]
Nice recovery :+1:

**Comment by ufodynasty** [comment]
This one actually works in code instead of just in math :(

**Comment by starg09** [comment]
Ohh, this looks way nicer! <3

**Pull request merged**
